spring:
  application:
    name: ms-customer
    
server:
   port:8930      
      
eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME: localhost}
